server:
  port: 8084
  servlet:
    context-path: '/ead-notification'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    output:
      ansi:
        enabled: Always
    rabbitmq:
      addresses: amqps://akfqarag:tbY1y22ne27yDy8P4YhyVaTzVVJq5S9O@woodpecker.rmq.cloudamqp.com/akfqarag

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
